# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Maven Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

#     export JAVA_TOOL_OPTIONS="-Djdk.util.zip.disableZip64ExtraFieldValidation=true \
# -Djdk.attach.allowAttachSelf=true \
# --add-opens=java.base/java.io=ALL-UNNAMED \
# --add-opens=java.base/sun.net.www.protocol.jar=ALL-UNNAMED \
# --add-opens=java.base/java.net=ALL-UNNAMED \
# --add-opens=java.naming/javax.naming.spi=ALL-UNNAMED \
# --add-opens=java.base/java.lang=ALL-UNNAMED"
    - name: Run the Maven verify phase
      run: MAVEN_OPS="-Djdk.util.zip.disableZip64ExtraFieldValidation=true -Djdk.attach.allowAttachSelf=true --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/sun.net.www.protocol.jar=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.naming/javax.naming.spi=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED" mvn --batch-mode --update-snapshots verify
